## 02 scikit-learn 中的 kNN 

In [26]:
import numpy as np
import matplotlib.pyplot as plt

In [27]:
raw_data_X = [[3.393533211, 2.331273381],
              [3.110073483, 1.781539638],
              [1.343808831, 3.368360954],
              [3.582294042, 4.679179110],
              [2.280362439, 2.866990263],
              [7.423436942, 4.696522875],
              [5.745051997, 3.533989803],
              [9.172168622, 2.511101045],
              [7.792783481, 3.424088941],
              [7.939820817, 0.791637231]
             ]
raw_data_y = [0, 0, 0, 0, 0, 1, 1, 1, 1, 1]

X_train = np.array(raw_data_X)
y_train = np.array(raw_data_y)

x = np.array([8.093607318, 3.365731514])

In [28]:
%run kNN_function/kNN.py

In [29]:
predict_y = kNN_classify(6, X_train, y_train, x)

In [30]:
predict_y

1

### 使用scikit-learn中的kNN

In [31]:
# sklearn中都是使用面向对象封装的
from sklearn.neighbors import KNeighborsClassifier

In [32]:
# 传入k值
kNN_classifier = KNeighborsClassifier(n_neighbors=6)

In [33]:
# fit，拟合过程
# 返回的是自己本身
# 此时这个实例中已经有模型了
kNN_classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=6, p=2,
                     weights='uniform')

In [34]:
# kNN_classifier.predict(x)   # 出错了，必须传入一个2D的array
kNN_classifier.predict(x.reshape((1, -1)))

array([1])

In [35]:
X_predict = x.reshape(1, -1)

In [36]:
X_predict

array([[8.09360732, 3.36573151]])

In [37]:
kNN_classifier.predict(X_predict)

array([1])

In [38]:
y_predict = kNN_classifier.predict(X_predict)

In [39]:
y_predict[0]

1

### 重新整理我们的kNN的代码

代码参见 [这里](kNN/KNN.py)

In [40]:
%run kNN/kNN.py

In [41]:
knn_clf = KNNClassifier(k=6)

In [42]:
knn_clf.fit(X_train, y_train)

KNN(k=6)

In [43]:
y_predict = knn_clf.predict(X_predict)

In [44]:
y_predict

array([1])

In [45]:
y_predict[0]

1