## 09 ``Numpy`` 中arg运算

In [134]:
import numpy as np

In [135]:
x = np.linspace(-10, 10, 21)

## 索引

In [136]:
# 求的是最小值的索引值
np.argmin(x)

0

In [137]:
x[np.argmin(x)]

-10.0

In [138]:
np.min(x)

-10.0

In [139]:
np.argmax(x)

20

In [140]:
x[np.argmax(x)]

10.0

In [141]:
np.max(x)

10.0

## 排序和使用索引

In [142]:
x = np.linspace(-10, 10, 21)
x

array([-10.,  -9.,  -8.,  -7.,  -6.,  -5.,  -4.,  -3.,  -2.,  -1.,   0.,
         1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [143]:
# 乱序处理
np.random.shuffle(x)
x

array([ -9.,   0.,  10.,   9., -10.,  -2.,   6.,   3.,  -1.,  -4.,  -3.,
         4.,  -7.,  -6.,   1.,  -8.,   7.,   5.,  -5.,   2.,   8.])

In [144]:
# 只是返回排好序的数列，本身没有排序
np.sort(x)

array([-10.,  -9.,  -8.,  -7.,  -6.,  -5.,  -4.,  -3.,  -2.,  -1.,   0.,
         1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [145]:
x

array([ -9.,   0.,  10.,   9., -10.,  -2.,   6.,   3.,  -1.,  -4.,  -3.,
         4.,  -7.,  -6.,   1.,  -8.,   7.,   5.,  -5.,   2.,   8.])

In [146]:
# 这个是数组原地排序
x.sort()

In [147]:
x

array([-10.,  -9.,  -8.,  -7.,  -6.,  -5.,  -4.,  -3.,  -2.,  -1.,   0.,
         1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [148]:
X = np.random.randint(10, size=(4,4))
X

array([[9, 3, 4, 0],
       [0, 2, 4, 7],
       [2, 4, 3, 4],
       [5, 0, 8, 1]])

In [149]:
# axis=0沿着行进行排序，也就是每一列都是有序的
np.sort(X, axis=0)

array([[0, 0, 3, 0],
       [2, 2, 4, 1],
       [5, 3, 4, 4],
       [9, 4, 8, 7]])

In [150]:
# axis=1沿着列进行排序，也就是每一行都是有序的
np.sort(X, axis=1)

array([[0, 3, 4, 9],
       [0, 2, 4, 7],
       [2, 3, 4, 4],
       [0, 1, 5, 8]])

## 使用索引

In [151]:
x

array([-10.,  -9.,  -8.,  -7.,  -6.,  -5.,  -4.,  -3.,  -2.,  -1.,   0.,
         1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [152]:
np.random.shuffle(x)

In [153]:
x

array([  9.,  -4.,   0.,  -7.,   6.,  -1.,   8.,   5.,   1.,  -6.,   4.,
         7.,   2.,  -2.,  10.,  -5.,  -3., -10.,  -9.,   3.,  -8.])

In [154]:
# 返回的是排好序的数组的元素的索引。第一个索引就是最小的元素
print(np.argsort(x))
print(x[np.argsort(x)[0]] == np.min(x))

[17 18 20  3  9 15  1 16 13  5  2  8 12 19 10  7  4 11  6  0 14]
True


In [155]:
# 快排中的partition，保证了索引为3的数字前面一定比索引为3的数字小，索引为3的数字后面的一定比索引为3的数字大
np.partition(x, 3)

array([ -9., -10.,  -8.,  -7.,  -6.,  -5.,  -1.,   3.,   1.,   0.,  -4.,
        -3.,   2.,  -2.,   4.,  10.,   7.,   5.,   8.,   6.,   9.])

In [156]:
# 上面方法的索引方法
np.argpartition(x, 3)

array([18, 17, 20,  3,  9, 15,  5, 19,  8,  2,  1, 16, 12, 13, 10, 14, 11,
        7,  6,  4,  0], dtype=int64)

In [157]:
X

array([[9, 3, 4, 0],
       [0, 2, 4, 7],
       [2, 4, 3, 4],
       [5, 0, 8, 1]])

In [178]:
# 每一行的排序结果的索引值。
print(np.argsort(X, axis=1))
for i in range(X.shape[0]):
    print(X[i, np.argsort(X, axis=1)[i, 0]] == np.min(X, axis=1)[i])

[[3 1 2 0]
 [0 1 2 3]
 [0 2 1 3]
 [1 3 0 2]]
True
True
True
True


In [159]:
# 分位的求索引
np.argpartition(X, 2, axis=1)

array([[3, 1, 2, 0],
       [0, 1, 2, 3],
       [0, 2, 1, 3],
       [1, 3, 0, 2]], dtype=int64)