## 03 测试我们的算法

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets 

In [2]:
iris = datasets.load_iris()
iris.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [3]:
X = iris.data

In [4]:
y = iris.target

In [5]:
X.shape

(150, 4)

In [6]:
y.shape

(150,)

### train_test_split

分离出一部分数据做训练，另外一部分数据做测试。
不能简单的使用切片对X和y进行训练和测试分离，因为看看y的数据就知道元数据可能是有顺序的。所以最好进行乱序化处理
但是X和y是对应的，不能各自乱序化
可以合并起来进行乱序化
或者直接获得乱序化的索引

In [7]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
# np.random.permutation是对上限以内的数字进行乱序排序
shuffled_indexes = np.random.permutation(len(X))
shuffled_indexes

array([ 12, 106,  60,  10, 131, 100, 148,  82,  52,  91,  56,   1,  41,
        30, 147,  73,  57, 144,  75,   6, 128,  96,   2,  55,  25,   4,
       113,  50,  22, 115,  20,   7, 141, 126,  21, 124, 139,  14, 146,
        18,  37, 140,  44, 125,  72,  48,  65, 102,   0,  31,  89,   9,
       101, 105,  70,  58,  95,  35,  15,  29, 107,  32,  78, 145, 116,
       136,  90,  36,  63,  61, 137, 130,  17,  26, 129,  33, 104,  97,
       120,  87,  85,  27, 123,  94,  67,  83,  16,   5,  93,  69,  99,
       114,  47,  42, 138, 108, 135, 112,  76, 118, 110,  38,  24, 111,
       149, 122,  64,  66,  54, 134, 142, 103,  74, 117,  77,  59,  51,
       121,  28,  43,  11,  45,  84,  68,  62,  92, 127,  53,  71,  81,
        49,  46, 109,   3,  19, 143,   8, 119,  98,  88, 132,  23,  34,
        79,  80,  86,  39, 133,  40,  13])

In [9]:
# 测试数据集个数
test_ratio = 0.2
# 去掉小数
test_size = int(len(X) * test_ratio)

In [10]:
test_indexes = shuffled_indexes[:test_size]
train_indexes = shuffled_indexes[test_size:]

In [11]:
X_train = X[train_indexes]
y_train = y[train_indexes]

X_test = X[test_indexes]
y_test = y[test_indexes]

In [12]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [13]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


#### 封装

In [14]:
from playML.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y)

In [15]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [16]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


#### 测试我们的算法

In [17]:
from playML.kNN import KNNClassifier

my_knn_clf = KNNClassifier(k=3)
my_knn_clf.fit(X_train, y_train)
y_predict = my_knn_clf.predict(X_test)

In [18]:
y_predict

array([1, 0, 0, 0, 0, 0, 0, 2, 0, 1, 2, 0, 2, 1, 1, 2, 1, 1, 2, 2, 1, 1,
       2, 0, 0, 1, 1, 2, 2, 0])

In [19]:
y_test

array([1, 0, 0, 0, 0, 0, 0, 2, 0, 1, 2, 0, 2, 1, 1, 2, 1, 1, 2, 2, 1, 1,
       2, 0, 0, 1, 2, 2, 2, 0])

In [20]:
# 看一下预测准确率，也就是y_predict和测试集相等的元素个数
sum(y_predict == y_test)

29

In [21]:
# 算出预测准确率
sum(y_predict == y_test) / len(y_test)

0.9666666666666667

#### sklearn中的train_test_split

In [22]:
from sklearn.model_selection import train_test_split

train_test_split

<function sklearn.model_selection._split.train_test_split(*arrays, **options)>

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=666)

In [24]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [25]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)
