## 10 ``Numpy`` 中的比较和Fancy Indexing

## Fancy Indexing

In [2]:
import numpy as np

x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [3]:
x[3]

3

In [4]:
x[3:9]

array([3, 4, 5, 6, 7, 8])

In [5]:
# 切片的方式必须等长
x[3:9:2]

array([3, 5, 7])

In [41]:
[x[3], x[5], x[8]]

[3, 5, 8]

In [42]:
# 所以numpy提供了非常方便的取出任意索引组的方法
ind = [3, 5, 8]
x[ind]

array([3, 5, 8])

In [8]:
# 可以二维数组，二维矩阵对应的是每一个索引
ind = np.array([[0, 2], [1, 3]])
x[ind]

array([[0, 2],
       [1, 3]])

## Fancy Indexing 应用在二维数组

In [9]:
X = x.reshape(4, -1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [43]:
# 感兴趣的是(0, 1),(1, 2),(2, 3)
row = np.array([0, 1, 2])
col = np.array([1, 2, 3])
X[row, col]

array([ 1,  6, 11])

In [11]:
# (0, 1), (0, 2), (0, 3)
X[0, col]

array([1, 2, 3])

In [12]:
# (0, 1), (0, 2), (0, 3), (1, 1), (1, 2), (1, 3)
X[:2, col]

array([[1, 2, 3],
       [5, 6, 7]])

In [13]:
col = [True, False, True, True]

In [14]:
# 对true的部分感兴趣
# 这种用法非常重要
X[0, col]

array([0, 2, 3])

## ``numpy.array`` 的比较

In [15]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [16]:
# x中所有元素和3相比
x < 3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [17]:
x > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [18]:
x <= 3

array([ True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [19]:
x >= 3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [20]:
x == 3

array([False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [21]:
x != 3

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [22]:
2 * x == 24 - 4 * x

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False])

In [23]:
X < 6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

## 使用 ``numpy.array`` 的比较结果 

In [24]:
# 这个也可以求<=3的元素
np.count_nonzero( x <= 3)

4

In [25]:
# 求出有多少个<=3的元素
np.sum(x <= 3)

4

In [26]:
# 每一列有多少个偶数
np.sum(X % 2 == 0, axis=0)

array([4, 0, 4, 0])

In [27]:
# 每一行有多少个偶数
np.sum(X % 2 == 0, axis=1)

array([2, 2, 2, 2])

In [28]:
# 是否有任意一个==0
np.any(x == 0)

True

In [29]:
# 是否有任意一个<0
np.any(x < 0)

False

In [30]:
np.all(x > 0)

False

In [31]:
np.all(x >= 0)

True

In [32]:
# 沿着列的方向，也就是看每一行是否都大于0
np.all(X > 0, axis=1)

array([False,  True,  True,  True])

In [33]:
# 这个是位运算符。不是条件运算符。
# 现在需要的是每一个数组进行独自运算，然后两个数组再合并，最后还是一个数组
# 两个数组每一个元素看作一位，非常类似位运算符
np.sum((x > 3) & (x < 10))

6

In [34]:
# 不是条件运算符
# np.sum((x > 3) && (x < 10))

SyntaxError: invalid syntax (<ipython-input-34-d834f65999a2>, line 1)

In [35]:
np.sum((x % 2 == 0) | (x > 10))

11

In [36]:
# 非运算
np.sum(~(x == 0))

15

## 比较结果和Fancy Indexing

In [37]:
x < 5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False, False, False])

In [38]:
# <5的值到底是哪一些
x[x < 5]

array([0, 1, 2, 3, 4])

In [39]:
x[x % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [45]:
print(X)
# 看每一行的索引为3的元素，能被3整除的行提取出来
print(X[X[:,3] % 3 == 0, :])
print(X[X[:,-1] % 3 == 0, :])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3]
 [12 13 14 15]]
[[ 0  1  2  3]
 [12 13 14 15]]
