## 08 ``Numpy`` 中的聚合操作

## sum

In [3]:
import numpy as np

L = np.random.random(100)
sum(L)

54.406852984527816

In [4]:
np.sum(L)

54.40685298452781

In [5]:
# np中的sum的效率高！
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

78 ms ± 212 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
819 µs ± 11.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


## min, max

In [6]:
np.min(big_array)

9.501370793474351e-07

In [7]:
np.max(big_array)

0.9999991543064245

In [8]:
# big_array中不太全，尽量使用np中的方法
big_array.min()

9.501370793474351e-07

In [9]:
big_array.max()

0.9999991543064245

In [10]:
big_array.sum()

500133.52839085093

### 多维度聚合

In [11]:
X = np.arange(16).reshape(4,-1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [12]:
# 不管维度，默认所有元素的和
np.sum(X)

120

In [13]:
# axis=0是每一列的和。axis=0是指沿着行这个方向进行运算
# axis传入的可以理解为被压缩掉的维度。0就是压缩掉行，只剩下列
np.sum(X, axis=0)

array([24, 28, 32, 36])

In [14]:
# axis=1是每一行的和。axis=1是指沿着列这个方向进行运算
np.sum(X, axis=1)

array([ 6, 22, 38, 54])

*注意：axis描述的是将要被压缩的维度。*

### 其他聚合操作

In [15]:
np.prod(X)

0

In [16]:
# 所有元素的乘积
np.prod(X + 1)

2004189184

In [17]:
# 均值
np.mean(X)

7.5

In [18]:
# 中位数
np.median(X)

7.5

In [19]:
# 异常值对平均数的影响过大
v = np.array([1, 1, 2, 2, 10])
np.mean(v)

3.2

In [20]:
np.median(v)

2.0

In [21]:
# %50的百分位
np.percentile(big_array, q=50)

0.49975945101334784

In [22]:
np.median(big_array)

0.49975945101334784

In [23]:
# 最大值
np.percentile(big_array, q=100)

0.9999991543064245

In [24]:
np.max(big_array)

0.9999991543064245

In [25]:
# 一边看这几个百分点就能看出分布
for percent in [0, 25, 50, 75, 100]:
    print(np.percentile(big_array, q=percent))

9.501370793474351e-07
0.250266373380963
0.49975945101334784
0.7500123443234672
0.9999991543064245


In [26]:
# 方差
np.var(big_array)

0.08331921851401417

In [27]:
# 标准差
np.std(big_array)

0.288650685975305

In [28]:
x = np.random.normal(0, 1, 1000000)

In [29]:
np.mean(x)

0.0009186836023089008

In [30]:
np.std(x)

0.9995089112318769